# Generated by Django 3.2.6 on 2021-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_name_snacks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='description',
            field=models.TextField(default='', max_length=64),
        ),
    ]
